version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 1337:1337
      - 9229:9229
      - 24678:24678
    environment:
      - MONGO_HOST=mongo
    env_file:
      - .env
    volumes:
      # bind project root during development for HMR
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./views:/usr/src/app/views
      - type: bind
        source: /srv/media
        target: /opt/app/media
    command: npm run dev

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
