version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      # node server port
      - 3201:3201
      # node debug port
      - 9229:9229
      - 24678:24678
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      # bind project root during development for HMR
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./common:/usr/src/app/common
      - ./views:/usr/src/app/views
      - type: bind
        source: /srv/media
        target: /opt/app/media
    command: pnpm dev

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  redis:
    image: redis:7.0-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - 6379:6379
    volumes:
      - redis:/data/cache

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 3200:3200
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Provide path to local certs
      # If not using SSL (locally) remove these and remove SSL from nginx.conf
      - /etc/ssl/chill.crt:/etc/ssl/chill.crt
      - /etc/ssl/chill.key:/etc/ssl/chill.key
    depends_on:
      - app

volumes:
  mongodb:
  mongodb_config:
  redis:
