services:
  app:
    build:
      context: .
    ports:
      # node server port
      - 3200:3200
      # node debug port
      - 9229:9229
      - 24678:24678
    env_file:
      - .env
    volumes:
      # bind project root during development for HMR
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./common:/usr/src/app/common
      - ./views:/usr/src/app/views
      - type: bind
        source: /srv/chill/media
        target: /opt/app/media
      - type: bind
        source: /srv/chill/data
        target: /opt/app/data
    command: pnpm dev
    depends_on:
      - postgres
      - redis
      - elasticsearch

  postgres:
    image: postgres:16-alpine
    container_name: chill-database
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chill-database-2-gui
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    image: redis:7.0-alpine
    container_name: chill-cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - 6379:6379
    volumes:
      - redis:/data/cache

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: chill-search
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${SEARCH_ENGINE_PASSWORD}
    volumes:
      - elastic-search:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  postgres:
  pgadmin:
  redis:
  elastic-search:
