version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      # node server port
      - 3200:3200
      # node debug port
      - 9229:9229
      - 24678:24678
    env_file:
      - .env
    volumes:
      # bind project root during development for HMR
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - ./common:/usr/src/app/common
      - ./views:/usr/src/app/views
      - type: bind
        source: /srv/media
        target: /opt/app/media
    command: pnpm dev
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  redis:
    image: redis:7.0-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - 6379:6379
    volumes:
      - redis:/data/cache

volumes:
  mongodb:
  mongodb_config:
  redis:
