version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 6400:6400
      - 9229:9229
    environment:
      - MONGO_HOST=mongo
      - HOST=localhost
    volumes:
      - type: bind
        source: /srv/media
        target: /opt/app/media
    command: npm run start:dev

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
